apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-dimple
spec:
  selector:
    app: aff-app-mongo
  ports:
    - port: 3015
      targetPort: 3015
      protocol: TCP
  type: NodePort # Use ClusterIP or NodePort based on your requirements
